### ISSUE TITLE
Prolog lab checker showing "solved exercise" message even though not solved

### ISSUE THREAD

**Issue by florinrm** [cs-pub-ro/PP-laboratoare#32]
Steps to reproduce:
1) go to the solution file (lab 10 for example)
2) go to a random exercise (it doesn't matter which one)
3) set the exercise implementation with the default one from skeleton
4) run the checker, which will show both `Nerezolvat.` and `Exercițiul X rezolvat corect!`

**Comment by andreiolaru-ro** [comment]
Solved by removal of the message.
