### ISSUE TITLE
Testul la ex 1 merge și pe liste

### ISSUE THREAD

**Issue by andreiolaru-ro** [cs-pub-ro/PP-laboratoare#7]
(define (list->stream L)
  (if(null? L)
  '()
  (stream-cons (car L) (cdr L))))

**Comment by florinrm** [comment]
> (define (list->stream L) (if(null? L) '() (stream-cons (car L) (cdr L))))

@andreiolaru-ro am putea sa adaugam un check in teste in care sa vedem daca rezultatul de la `list->stream` este o lista. Ce zici? Daca este lista, atunci testul sa pice.

**Comment by florinrm** [comment]
@andreiolaru-ro Testele trec si daca avem asa:
```lisp
(define (list->stream L)
  (if (null? L)
      '()
      (stream-cons (car L) (list->stream (cdr L)))))
```

Aici propun sa adaugam un test pentru cazul `(list->stream '())`, in care sa verificam `(null? (list->stream '())`, care, in mod corect, da false (testat pe solutia oficiala)

**Comment by florinrm** [comment]
De asemenea, toate testele (inclusiv de la exercitiul 1) trec pentru urmatoarea solutie (proasta):
```lisp
(define (list->stream L)
  (if (null? L)
      '()
      (cons (car L) (cdr L))))
```
Aici ne trebuie un test in care sa vedem daca rezultatul intors este o lista sau nu.
